# Data Wrangling
- Reading Data
- QC (*especially* missing values or `NaN`)
-` .groupby()` and `value_counts()`
- Subsetting (boolean selection)
- Adding Columns
- Sorting

In [1]:
1+1

2

In [12]:
import pandas as pd
ab = pd.read_csv("../../amazonbooks.csv", encoding = "ISO-8859-1")

In [8]:
! ls ../..

amazonbooks.csv				   STA130_F23_Syllabus_html2.ipynb
avatar.csv				   STA130_F23_Syllabus_html.ipynb
challengerdata.csv			   STA130_F23_Syllabus.ipynb
coffee_ratings.csv			   STA130_HW_1.ipynb
course_project_template			   STA130_HW_1_tester.ipynb
DoSS_W23_Departmental_Meeting_MScAC.ipynb  STA130_HW_2.ipynb
F22-ProjectTemplate.git			   STA130_HW_2_tester.ipynb
F22_STA130				   STA130_MT.ipynb
HorP_DT					   STA130_ProblemSet1
HorP_DT.pdf				   STA130_ProblemSet2
hw3					   STA130_ProblemSet3
hw4					   STA130_ProblemSet6
hw5					   STA130_ProblemSet7-Week8
hw6					   STA130_ProblemSet8-Week10
hw7					   STA130_ProblemSet9-Week11
hw8					   STA130_TUT_1
hw9					   STA130_TUT_1-2.ipynb
im					   STA130_TUT_2
mscac					   STA130_TUT_2.ipynb
oly12athletes.csv			   STA130-W22-ProblemSet6.git
oly12countries.csv			   STA130-W22-ProblemSet9.git
preamble.tex				   STA130_Week11_Demo
pymc.ipynb				   STA130_Week12_Slides
scikit_learn_data			   STA130_Week1_Demo
shared					   STA130_Week1_Slides
shared-readwrite			   STA130_Week3_Slides
STA130-F21-mod4n5-BIGDOC-extras		   STA130_Week8_Slides
STA130_F23				   STA410_W23_Syllabus
STA130_F23_C10.ipynb			   STA410_W23_Week1_HW
STA130_F23_C3.ipynb			   STA410_W23_Week1_Reading
STA130_F23_C4.ipynb			   stat_excom_F22.pdf
STA130_F23_C5.ipynb			   stat_excom_F22.Rmd
STA130_F23_C5_v2.ipynb			   superbowl_ads.csv
STA130_F23_C6.ipynb			   titanic.csv
STA130_F23_C6_v2.ipynb			   Untitled1.ipynb
STA130_F23_C7.ipynb			   Untitled2.ipynb
STA130_F23_C8.ipynb			   Untitled3.ipynb
STA130_F23_C9.ipynb			   Untitled4.ipynb
STA130_F23_CP				   Untitled.ipynb
STA130_F23_Syllabus-2.ipynb		   W22
STA130_F23_Syllabus-4html.ipynb		   W22_410

In [14]:
ab

,Title,Author,List Price,Amazon Price,Hard_or_Paper,NumPages,Publisher,Pub year,ISBN-10,Height,Width,Thick,Weight_oz
0,"1,001 Facts that Will Scare the S#*t Out of Yo...",Cary McNeal,12.95,5.18,P,304.0,Adams Media,2010.0,1605506249,7.8,5.5,0.8,11.2
1,21: Bringing Down the House - Movie Tie-In: Th...,Ben Mezrich,15.00,10.20,P,273.0,Free Press,2008.0,1416564195,8.4,5.5,0.7,7.2
2,100 Best-Loved Poems (Dover Thrift Editions),Smith,1.50,1.50,P,96.0,Dover Publications,1995.0,486285537,8.3,5.2,0.3,4.0
3,1421: The Year China Discovered America,Gavin Menzies,15.99,10.87,P,672.0,Harper Perennial,2008.0,61564893,8.8,6.0,1.6,28.8
4,1493: Uncovering the New World Columbus Created,Charles C. Mann,30.50,16.77,P,720.0,Knopf,2011.0,307265722,8.0,5.2,1.4,22.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,Where the Sidewalk Ends,Shel Silverstein,18.99,12.24,H,192.0,HarperCollins,2004.0,60572345,9.3,6.6,1.1,24.0
321,White Privilege,Paula S. Rothenberg,27.55,27.55,P,160.0,Worth Publishers,2011.0,1429233443,9.1,6.1,0.7,8.0
322,Why I wore lipstick,Geralyn Lucas,12.95,5.18,P,224.0,St Martin's Griffin,2005.0,031233446X,8.0,5.4,0.7,6.4
323,"Worlds Together, Worlds Apart: A History of th...",Robert Tignor,97.50,97.50,P,480.0,W. W. Norton & Company,2010.0,393934942,10.7,8.9,0.9,14.4
324,Wuthering Heights,Emily Bronte,16.99,4.95,P,344.0,CreatSpace,2011.0,1463533411,7.8,5.1,1.0,16.0

In [15]:
ab.shape

(325, 13)

In [16]:
ab.describe()

,List Price,Amazon Price,NumPages,Pub year,Height,Width,Thick,Weight_oz
count,324.000000,325.000000,323.000000,324.000000,321.000000,320.000000,324.000000,316.000000
mean,18.579753,13.333846,335.857585,2002.206790,8.163240,5.585000,0.907716,12.487975
std,14.252829,13.727679,161.984389,10.629002,0.918739,0.874057,0.368625,6.644648
min,1.500000,0.770000,24.000000,1936.000000,5.100000,4.100000,0.100000,1.200000
25%,13.950000,8.600000,208.000000,1998.000000,7.900000,5.200000,0.600000,7.800000
50%,15.000000,10.200000,320.000000,2005.000000,8.100000,5.400000,0.900000,11.200000
75%,19.950000,13.130000,416.000000,2010.000000,8.500000,5.900000,1.100000,16.000000
max,139.950000,139.950000,896.000000,2011.000000,12.100000,9.500000,2.100000,35.200000

In [17]:
# ab.describe() is a METHOD (function)
# this is an attribute
ab.dtypes

Title             object
Author            object
List Price       float64
Amazon Price     float64
Hard_or_Paper     object
NumPages         float64
Publisher         object
Pub year         float64
ISBN-10           object
Height           float64
Width            float64
Thick            float64
Weight_oz        float64
dtype: object

In [21]:
# pd.Series / pd.DataFrame
(ab.Hard_or_Paper == 'H').sum()# coercion

89

In [22]:
ab.Hard_or_Paper.astype("category")

0      P
1      P
2      P
3      P
4      P
      ..
320    H
321    P
322    P
323    P
324    P
Name: Hard_or_Paper, Length: 325, dtype: category
Categories (2, object): ['H', 'P']

In [23]:
ab.Hard_or_Paper = ab.Hard_or_Paper.astype("category")

In [25]:
ab.dtypes

Title              object
Author             object
List Price        float64
Amazon Price      float64
Hard_or_Paper    category
NumPages          float64
Publisher          object
Pub year          float64
ISBN-10            object
Height            float64
Width             float64
Thick             float64
Weight_oz         float64
dtype: object

In [30]:
ab.dropna().shape

(310, 13)

In [32]:
ab.isnull().sum()

Title            0
Author           1
List Price       1
Amazon Price     0
Hard_or_Paper    0
NumPages         2
Publisher        1
Pub year         1
ISBN-10          0
Height           4
Width            5
Thick            1
Weight_oz        9
dtype: int64

In [33]:
# chaining methods! ya cul
ab.dropna().isnull().sum()

Title            0
Author           0
List Price       0
Amazon Price     0
Hard_or_Paper    0
NumPages         0
Publisher        0
Pub year         0
ISBN-10          0
Height           0
Width            0
Thick            0
Weight_oz        0
dtype: int64

In [34]:
#ab.dropna(inplace=True)
ab = ab.dropna()

In [35]:
ab['Pub year'] = ab['Pub year'].astype(int)
ab

/tmp/ipykernel_203/1078008371.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ab['Pub year'] = ab['Pub year'].astype(int)

,Title,Author,List Price,Amazon Price,Hard_or_Paper,NumPages,Publisher,Pub year,ISBN-10,Height,Width,Thick,Weight_oz
0,"1,001 Facts that Will Scare the S#*t Out of Yo...",Cary McNeal,12.95,5.18,P,304.0,Adams Media,2010,1605506249,7.8,5.5,0.8,11.2
1,21: Bringing Down the House - Movie Tie-In: Th...,Ben Mezrich,15.00,10.20,P,273.0,Free Press,2008,1416564195,8.4,5.5,0.7,7.2
2,100 Best-Loved Poems (Dover Thrift Editions),Smith,1.50,1.50,P,96.0,Dover Publications,1995,486285537,8.3,5.2,0.3,4.0
3,1421: The Year China Discovered America,Gavin Menzies,15.99,10.87,P,672.0,Harper Perennial,2008,61564893,8.8,6.0,1.6,28.8
4,1493: Uncovering the New World Columbus Created,Charles C. Mann,30.50,16.77,P,720.0,Knopf,2011,307265722,8.0,5.2,1.4,22.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,Where the Sidewalk Ends,Shel Silverstein,18.99,12.24,H,192.0,HarperCollins,2004,60572345,9.3,6.6,1.1,24.0
321,White Privilege,Paula S. Rothenberg,27.55,27.55,P,160.0,Worth Publishers,2011,1429233443,9.1,6.1,0.7,8.0
322,Why I wore lipstick,Geralyn Lucas,12.95,5.18,P,224.0,St Martin's Griffin,2005,031233446X,8.0,5.4,0.7,6.4
323,"Worlds Together, Worlds Apart: A History of th...",Robert Tignor,97.50,97.50,P,480.0,W. W. Norton & Company,2010,393934942,10.7,8.9,0.9,14.4
324,Wuthering Heights,Emily Bronte,16.99,4.95,P,344.0,CreatSpace,2011,1463533411,7.8,5.1,1.0,16.0

In [36]:
ab.dtypes

Title              object
Author             object
List Price        float64
Amazon Price      float64
Hard_or_Paper    category
NumPages          float64
Publisher          object
Pub year            int64
ISBN-10            object
Height            float64
Width             float64
Thick             float64
Weight_oz         float64
dtype: object

In [39]:
ab.groupby("Hard_or_Paper").NumPages.mean()

Hard_or_Paper
H    321.128205
P    333.754310
Name: NumPages, dtype: float64

In [40]:
ab.groupby("Hard_or_Paper").NumPages.sum()

Hard_or_Paper
H    25048.0
P    77431.0
Name: NumPages, dtype: float64

In [42]:
ab.groupby("Hard_or_Paper").NumPages.count()#/.size()

Hard_or_Paper
H     78
P    232
Name: NumPages, dtype: int64

In [43]:
ab.groupby("Hard_or_Paper").NumPages.max()

Hard_or_Paper
H    880.0
P    896.0
Name: NumPages, dtype: float64

In [46]:
ab.groupby("Hard_or_Paper").NumPages.quantile(.04)

Hard_or_Paper
H     33.76
P    128.00
Name: NumPages, dtype: float64

In [51]:
ab[['NumPages', 'List Price', 'Amazon Price']].groupby("Hard_or_Paper").mean()

KeyError: 'Hard_or_Paper'

In [50]:
ab[['NumPages', 'List Price', 'Amazon Price', "Hard_or_Paper"]].groupby("Hard_or_Paper").mean()

                 NumPages  List Price  Amazon Price
Hard_or_Paper
H              321.128205   20.203462     12.962821
P              333.754310   17.171681     12.461509

In [52]:
ab['Publisher'].value_counts()

Vintage                     37
Grand Central Publishing    10
Washington Square Press      7
Mariner Books                7
Harper Paperbacks            7
                            ..
Warner Books                 1
Wm. B. Eerdmans              1
North Atlantic Books         1
Wolfgang Publications        1
St Martin's Griffin          1
Name: Publisher, Length: 153, dtype: int64

In [53]:
ab.head()

,Title,Author,List Price,Amazon Price,Hard_or_Paper,NumPages,Publisher,Pub year,ISBN-10,Height,Width,Thick,Weight_oz
0,"1,001 Facts that Will Scare the S#*t Out of Yo...",Cary McNeal,12.95,5.18,P,304.0,Adams Media,2010,1605506249,7.8,5.5,0.8,11.2
1,21: Bringing Down the House - Movie Tie-In: Th...,Ben Mezrich,15.00,10.20,P,273.0,Free Press,2008,1416564195,8.4,5.5,0.7,7.2
2,100 Best-Loved Poems (Dover Thrift Editions),Smith,1.50,1.50,P,96.0,Dover Publications,1995,486285537,8.3,5.2,0.3,4.0
3,1421: The Year China Discovered America,Gavin Menzies,15.99,10.87,P,672.0,Harper Perennial,2008,61564893,8.8,6.0,1.6,28.8
4,1493: Uncovering the New World Columbus Created,Charles C. Mann,30.50,16.77,P,720.0,Knopf,2011,307265722,8.0,5.2,1.4,22.4

In [55]:
ab[0:5] # ab[:5]

,Title,Author,List Price,Amazon Price,Hard_or_Paper,NumPages,Publisher,Pub year,ISBN-10,Height,Width,Thick,Weight_oz
0,"1,001 Facts that Will Scare the S#*t Out of Yo...",Cary McNeal,12.95,5.18,P,304.0,Adams Media,2010,1605506249,7.8,5.5,0.8,11.2
1,21: Bringing Down the House - Movie Tie-In: Th...,Ben Mezrich,15.00,10.20,P,273.0,Free Press,2008,1416564195,8.4,5.5,0.7,7.2
2,100 Best-Loved Poems (Dover Thrift Editions),Smith,1.50,1.50,P,96.0,Dover Publications,1995,486285537,8.3,5.2,0.3,4.0
3,1421: The Year China Discovered America,Gavin Menzies,15.99,10.87,P,672.0,Harper Perennial,2008,61564893,8.8,6.0,1.6,28.8
4,1493: Uncovering the New World Columbus Created,Charles C. Mann,30.50,16.77,P,720.0,Knopf,2011,307265722,8.0,5.2,1.4,22.4

In [58]:
ab.loc[:5, ['NumPages','Publisher']]

   NumPages           Publisher
0     304.0         Adams Media
1     273.0          Free Press
2      96.0  Dover Publications
3     672.0    Harper Perennial
4     720.0               Knopf
5     460.0               Knopf

In [60]:
ab.iloc[[2,6,8,11], [0,3]]

                                                Title  Amazon Price
2        100 Best-Loved Poems (Dover Thrift Editions)          1.50
6   A Christmas Carol and Other Christmas Writings...         13.46
9                                  A Farewell To Arms         19.80
12  A Guide to the Good Life: The Ancient Art of S...         13.57

In [61]:
ab.iloc[10:-290, [0,3]]

                                                Title  Amazon Price
11          A Game of Thrones: A song of fire and ice         10.46
12  A Guide to the Good Life: The Ancient Art of S...         13.57
13  A Hammock Beneath the Mangoes: Stories from La...         14.60
14  A Holocaust Reader: Responses to the Nazi Exte...         37.95
15                               A Light in the Attic         11.58
16      A Midsummer Night's dream No Fear Shakespeare          3.99
17                                    A Painted House         10.20
18                                A Raisin In The Sun          5.87
19                                A Raisin in the Sun         10.85
20                                      A Small Place         10.40

In [62]:
# boolean selection
ab[ab['Hard_or_Paper']=='P']

,Title,Author,List Price,Amazon Price,Hard_or_Paper,NumPages,Publisher,Pub year,ISBN-10,Height,Width,Thick,Weight_oz
0,"1,001 Facts that Will Scare the S#*t Out of Yo...",Cary McNeal,12.95,5.18,P,304.0,Adams Media,2010,1605506249,7.8,5.5,0.8,11.2
1,21: Bringing Down the House - Movie Tie-In: Th...,Ben Mezrich,15.00,10.20,P,273.0,Free Press,2008,1416564195,8.4,5.5,0.7,7.2
2,100 Best-Loved Poems (Dover Thrift Editions),Smith,1.50,1.50,P,96.0,Dover Publications,1995,486285537,8.3,5.2,0.3,4.0
3,1421: The Year China Discovered America,Gavin Menzies,15.99,10.87,P,672.0,Harper Perennial,2008,61564893,8.8,6.0,1.6,28.8
4,1493: Uncovering the New World Columbus Created,Charles C. Mann,30.50,16.77,P,720.0,Knopf,2011,307265722,8.0,5.2,1.4,22.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,We have never been modern,Bruno Latour,26.00,19.01,P,168.0,Harvard University Press,1993,674948394,8.9,6.0,0.5,7.0
321,White Privilege,Paula S. Rothenberg,27.55,27.55,P,160.0,Worth Publishers,2011,1429233443,9.1,6.1,0.7,8.0
322,Why I wore lipstick,Geralyn Lucas,12.95,5.18,P,224.0,St Martin's Griffin,2005,031233446X,8.0,5.4,0.7,6.4
323,"Worlds Together, Worlds Apart: A History of th...",Robert Tignor,97.50,97.50,P,480.0,W. W. Norton & Company,2010,393934942,10.7,8.9,0.9,14.4
324,Wuthering Heights,Emily Bronte,16.99,4.95,P,344.0,CreatSpace,2011,1463533411,7.8,5.1,1.0,16.0

In [64]:
ab[ab.NumPages>300]

,Title,Author,List Price,Amazon Price,Hard_or_Paper,NumPages,Publisher,Pub year,ISBN-10,Height,Width,Thick,Weight_oz
0,"1,001 Facts that Will Scare the S#*t Out of Yo...",Cary McNeal,12.95,5.18,P,304.0,Adams Media,2010,1605506249,7.8,5.5,0.8,11.2
3,1421: The Year China Discovered America,Gavin Menzies,15.99,10.87,P,672.0,Harper Perennial,2008,61564893,8.8,6.0,1.6,28.8
4,1493: Uncovering the New World Columbus Created,Charles C. Mann,30.50,16.77,P,720.0,Knopf,2011,307265722,8.0,5.2,1.4,22.4
5,1861: The Civil War Awakening,Adam Goodheart,28.95,16.44,H,460.0,Knopf,2011,1400040159,8.9,6.3,1.7,32.0
6,A Christmas Carol and Other Christmas Writings...,Dickens,20.00,13.46,H,336.0,Penguin Classics Hardcover,2010,141195851,7.8,5.3,1.2,15.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
316,Waiting,Ha Jin,15.00,10.20,P,308.0,Vintage,2000,375706410,8.0,5.2,0.7,10.4
317,War Trash,Ha Jin,15.95,10.85,P,368.0,Vintage,2005,1400075793,7.9,5.2,0.9,10.4
318,Water for Elephants: A Novel,Gruen,14.95,8.14,P,350.0,Algonquin Books,2007,1565125606,8.2,5.4,1.0,12.8
323,"Worlds Together, Worlds Apart: A History of th...",Robert Tignor,97.50,97.50,P,480.0,W. W. Norton & Company,2010,393934942,10.7,8.9,0.9,14.4
324,Wuthering Heights,Emily Bronte,16.99,4.95,P,344.0,CreatSpace,2011,1463533411,7.8,5.1,1.0,16.0

In [70]:
ab[(ab.NumPages>400) | (ab.NumPages<50)]

,Title,Author,List Price,Amazon Price,Hard_or_Paper,NumPages,Publisher,Pub year,ISBN-10,Height,Width,Thick,Weight_oz
3,1421: The Year China Discovered America,Gavin Menzies,15.99,10.87,P,672.0,Harper Perennial,2008,61564893,8.8,6.0,1.6,28.8
4,1493: Uncovering the New World Columbus Created,Charles C. Mann,30.50,16.77,P,720.0,Knopf,2011,307265722,8.0,5.2,1.4,22.4
5,1861: The Civil War Awakening,Adam Goodheart,28.95,16.44,H,460.0,Knopf,2011,1400040159,8.9,6.3,1.7,32.0
7,A Confederacy of Dunces,John Kennedy Toole,15.00,8.44,P,405.0,Grove Weidenfeld,1987,802130208,8.2,5.3,0.8,11.2
10,A Fine Balance,Rohinton Mistry,17.00,8.97,P,624.0,Vintage,2001,140003065X,7.7,5.1,1.7,16.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,The Woman in White,Wilkie Collins,20.00,12.17,H,720.0,Penguin Classics,2010,141192449,7.9,5.3,1.7,28.8
306,To End All Wars: A Story of Loyalty and Rebell...,Adam Hochschild,28.00,16.08,H,480.0,Houghton Mifflin Harcourt,2011,618758283,9.1,6.2,1.7,25.6
308,To the End of the Land (Vintage International),Grossman,15.95,10.68,P,672.0,Vintage,2011,307476405,7.9,5.2,1.4,19.2
314,Unbroken,Laura Hillenbrand,27.00,13.49,H,496.0,Random House,2010,1400064163,9.4,6.3,1.7,28.0
323,"Worlds Together, Worlds Apart: A History of th...",Robert Tignor,97.50,97.50,P,480.0,W. W. Norton & Company,2010,393934942,10.7,8.9,0.9,14.4

In [72]:
ab[(ab.NumPages>400) & (ab.Hard_or_Paper=='H')]

,Title,Author,List Price,Amazon Price,Hard_or_Paper,NumPages,Publisher,Pub year,ISBN-10,Height,Width,Thick,Weight_oz
5,1861: The Civil War Awakening,Adam Goodheart,28.95,16.44,H,460.0,Knopf,2011,1400040159,8.9,6.3,1.7,32.0
24,A Year with C. S. Lewis: Daily Readings from H...,Lewis,22.99,15.63,H,416.0,HarperOne,2003,60566167,7.5,5.7,1.4,16.0
31,American Psycho,Ellis,15.95,8.39,H,416.0,Vintage,1991,679735771,8.0,5.3,0.9,12.8
49,Catch-22,Jospeh Heller,24.00,16.32,H,624.0,Everyman's Library,1995,679437223,8.4,5.3,1.4,22.4
65,Divergent,"Roth, Veronica",17.99,11.46,H,496.0,Katherine Tegen Books,2011,62024027,8.2,5.8,1.6,19.2
84,"Game Change: Obama and the Clintons, McCain an...",John Heilemann and Mark Halperin,27.99,11.20,H,464.0,Harper,2010,61733636,9.1,6.0,1.7,1.2
97,Hope Leslie,Sedgwick,17.00,11.55,H,448.0,Penguin Classics,1998,140436766,7.8,5.1,0.9,11.2
104,"In the Garden of Beasts: Love, Terror, and an ...",Erik Larson,26.00,13.00,H,464.0,Crown,2011,307408841,9.5,6.0,1.5,25.6
105,"In The Plex: How Google Thinks, Works, and Sha...",Levy,26.00,14.44,H,432.0,Simon & Schuster,2011,1416596585,9.4,6.2,1.4,22.4
112,Invisible Man,Ellison,21.00,13.43,H,624.0,Modern Library,1995,679601392,7.8,4.8,1.8,25.6
135,Middlemarch (Penguin Hardback Classics),Eliot,20.00,12.17,H,880.0,Penguin Classics Hardcover,2011,141196890,7.9,5.4,2.0,35.2
141,Nathaniel Hawthorne's Tales,Hawthorne,13.83,13.83,H,480.0,W. W. Norton & Co.,1987,393954269,8.5,5.2,1.0,17.6
150,Olive Twist,Charles Dickens,20.00,13.60,H,607.0,Penguin Classics,2010,141192496,7.9,5.1,1.5,24.0
221,The Classic Slave Narratives-paperback,Henry Gates,7.95,7.95,H,688.0,Signet Classics,2002,451528247,6.6,4.1,1.7,11.2
228,The Da Vinci Code,Brown,9.99,9.99,H,597.0,Anchor,2009,307474275,7.5,4.3,1.3,12.8
276,The Power of Six,"Lore, Pittacus",17.99,8.98,H,416.0,HarperCollins,2011,61974552,8.3,5.7,1.5,17.6
299,The Woman in White,Wilkie Collins,20.00,12.17,H,720.0,Penguin Classics,2010,141192449,7.9,5.3,1.7,28.8
306,To End All Wars: A Story of Loyalty and Rebell...,Adam Hochschild,28.00,16.08,H,480.0,Houghton Mifflin Harcourt,2011,618758283,9.1,6.2,1.7,25.6
314,Unbroken,Laura Hillenbrand,27.00,13.49,H,496.0,Random House,2010,1400064163,9.4,6.3,1.7,28.0

In [73]:
ab['list price dollars int'] = ab['List Price'].astype(int) 
ab

/tmp/ipykernel_203/3689582331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ab['list price dollars int'] = ab['List Price'].astype(int)

,Title,Author,List Price,Amazon Price,Hard_or_Paper,NumPages,Publisher,Pub year,ISBN-10,Height,Width,Thick,Weight_oz,list price dollars int
0,"1,001 Facts that Will Scare the S#*t Out of Yo...",Cary McNeal,12.95,5.18,P,304.0,Adams Media,2010,1605506249,7.8,5.5,0.8,11.2,12
1,21: Bringing Down the House - Movie Tie-In: Th...,Ben Mezrich,15.00,10.20,P,273.0,Free Press,2008,1416564195,8.4,5.5,0.7,7.2,15
2,100 Best-Loved Poems (Dover Thrift Editions),Smith,1.50,1.50,P,96.0,Dover Publications,1995,486285537,8.3,5.2,0.3,4.0,1
3,1421: The Year China Discovered America,Gavin Menzies,15.99,10.87,P,672.0,Harper Perennial,2008,61564893,8.8,6.0,1.6,28.8,15
4,1493: Uncovering the New World Columbus Created,Charles C. Mann,30.50,16.77,P,720.0,Knopf,2011,307265722,8.0,5.2,1.4,22.4,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,Where the Sidewalk Ends,Shel Silverstein,18.99,12.24,H,192.0,HarperCollins,2004,60572345,9.3,6.6,1.1,24.0,18
321,White Privilege,Paula S. Rothenberg,27.55,27.55,P,160.0,Worth Publishers,2011,1429233443,9.1,6.1,0.7,8.0,27
322,Why I wore lipstick,Geralyn Lucas,12.95,5.18,P,224.0,St Martin's Griffin,2005,031233446X,8.0,5.4,0.7,6.4,12
323,"Worlds Together, Worlds Apart: A History of th...",Robert Tignor,97.50,97.50,P,480.0,W. W. Norton & Company,2010,393934942,10.7,8.9,0.9,14.4,97
324,Wuthering Heights,Emily Bronte,16.99,4.95,P,344.0,CreatSpace,2011,1463533411,7.8,5.1,1.0,16.0,16

In [76]:
ab.sort_values(["Pub year", "NumPages"], ascending=False)

,Title,Author,List Price,Amazon Price,Hard_or_Paper,NumPages,Publisher,Pub year,ISBN-10,Height,Width,Thick,Weight_oz,list price dollars int
135,Middlemarch (Penguin Hardback Classics),Eliot,20.00,12.17,H,880.0,Penguin Classics Hardcover,2011,141196890,7.9,5.4,2.0,35.2,20
257,The Invisible Bridge (Vintage Contemporaries),Orringer,15.95,8.95,P,784.0,Vintage,2011,140003437,7.8,5.2,1.4,20.8,15
4,1493: Uncovering the New World Columbus Created,Charles C. Mann,30.50,16.77,P,720.0,Knopf,2011,307265722,8.0,5.2,1.4,22.4,30
11,A Game of Thrones: A song of fire and ice,George R.R. Martin,17.00,10.46,P,720.0,Bantam,2011,553386790,9.1,6.2,1.5,27.2,17
85,Game of Thrones,Martin,17.00,10.46,P,720.0,Bantam,2011,553386794,9.1,6.2,1.5,27.2,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Hop on Pop,Seuss,8.99,8.99,H,72.0,Beginner Books,1963,039480029X,9.3,6.7,0.4,14.4,8
126,Lord of the Flies,William Golding,9.99,9.99,P,208.0,Perigee Books,1959,399501487,7.2,4.2,0.6,4.0,9
220,The Cat in the Hat,Seuss,8.99,8.99,H,72.0,Random House Books,1957,717260593,9.3,6.8,0.4,8.5,8
138,Modern Man in Search of a Soul (Harvest Book),C.G. Jung,14.00,11.20,P,244.0,Harcourt Harvest,1955,156612062,8.0,5.3,0.6,6.4,14
291,The Story of Ferdinand,Munro Leaf,17.99,10.88,H,72.0,Viking Juvenile,1936,670674249,9.4,7.4,0.5,14.4,17